### PR TITLE
Closes #2. Renamed files in game/plugins/ to include capitals

### LINKED ISSUE #2: Using grunt
# When using grunt, I got this error:

```bash
Running "browserify:build" (browserify) task
>>Error: module "./plugins/Roads" not found from "/home/pablo/IsoCitySim/game/main.js"
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

### PR DESCRIPTION
**Pull request by tobbbles**
Grunt build was failing due to `main.js` looking for Roads, WorldManager, and Generate with capitals. Renamed the files so everything is kushty! :smile:

### CODE REVIEW

**Comment by snollygolly** [comment]
Was your build failing too?  It's strange because mine works just fine.

**Comment by mnzt** [comment]
Is `roads.js`, `worldmanager.js`, and `generate.js` in `./game/plugins/` capitalised?

**Comment by snollygolly** [comment]
screen shot 2016-01-11 at 7 32 40 am

Nope.  They look just like they do in the repo.

**Comment by mnzt** [comment]
Weird. What about line 6-8 of your `main.js`?

The repo's:
```
  var Roads = require('./plugins/Roads');
  var Generate = require('./plugins/Generate');
  var WorldManager = require('./plugins/WorldManager');
```

**Comment by snollygolly** [comment]
Looks the same, but it's definitely referencing an uppercase version, so I don't see any way this could hurt.  Could be system differences. :shipit:

**Pull request merged**
